name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
          echo "Installed dependencies:"
          npm list --depth=0

      - name: Grant execute permissions to vite binary
        run: |
          chmod +x ./node_modules/.bin/vite
          ls -l ./node_modules/.bin/vite

      - name: Build
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          npm run build
          echo "Build exit code: $?"

      - name: Debug Build Output
        run: |
          echo "Dist directory contents:"
          ls -lR dist
          echo "Disk usage:"
          du -sh dist
          echo "Total files in dist:"
          find dist -type f | wc -l

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}