name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start Server in Background
        run: |
          npm run start:server &
          sleep 10  # Increased wait time

      - name: Check Server Logs
        run: |
          ps aux | grep node
          netstat -tuln  # Check listening ports

      - name: Verify Server is Running
        run: |
          curl -v http://localhost:3002/api/rooms
          if [ $? -ne 0 ]; then
            echo "Server failed to start"
            exit 1
          fi

      - name: Grant execute permissions to vite binary
        run: |
          chmod +x ./node_modules/.bin/vite
          ls -l ./node_modules/.bin/vite

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages